#model: 'gemma:7b'
#model: 'dolphin-mistral:latest'
#model: 'mistral-openorca:latest'
model: 'mistral:instruct'

testData:
  path: '../data/raw/test.jsonl'
  num: 5
  selected:
#    - 5062276
#    - 2336970
#    - 3992375
#    - 440280
  # 代码变更无法提现注释变更
  - 6017988
  - 2248673
  # 术语修正
  - 5724303

params:
  nr_gen: 6 # 每个问题的初始生成候选数
  nr_cand1: 6 # 第一轮筛选后剩下的结果数
  nr_cand: 3 # 最后保留的候选结果数