#model: 'gemma:7b'
#model: 'dolphin-mistral:latest'
#model: 'mistral-openorca:latest'
#model: 'mistral:instruct'
#model: 'llama2:7b'
#model: qwen:7b
#model: deepseek-coder:6.7b
#model: solar:10.7b
#model: openhermes:7b-v2.5
model: llama3:instruct
#model: wizardlm2:7b
#model: phi3:3.8b

#rag_src: 'data/processed/train_clean.jsonl'

testData:
  path: 'data/raw/test_clean.jsonl'
  num: -1
  selected:
#    ## 论文：CUP
#    - 6104728 # @NativeType (" shaderc_spvc_compiler_t " )
#    - 4233657 # private String getSessionFileName
#    ## 论文：HatCUP
#    - 111342 # alkacon/opencms-core
#    - 235252 # Alluxio/alluxio

params:
  nr_gen: 5 # 每个问题的初始生成候选数